apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "locust.fullname" . }}-worker
  labels:
    {{- include "locust.labels" . | nindent 4 }}
    component: {{ include "locust.fullname" . }}-workers
spec:
  replicas: {{ .Values.workers.replicas }}
  selector:
    matchLabels:
      {{- include "locust.selectorLabels" . | nindent 6 }}
      component: {{ include "locust.fullname" . }}-workers
  serviceName: locust-worker
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/locust-script.yaml") . | sha256sum }}
      {{- with .Values.workers.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "locust.selectorLabels" . | nindent 8 }}
        component: {{ include "locust.fullname" . }}-workers
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "locust.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.workers.podSecurityContext | nindent 8 }}
      volumes:
        - name: locust-script
          configMap:
            name: {{ include "locust.fullname" . }}-script
      containers:
        - name: worker
          securityContext:
            {{- toYaml .Values.workers.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--worker", "--master-host={{ include "locust.fullname" . }}"]
          volumeMounts:
            - name: locust-script
              mountPath: /home/locust
          resources:
            {{- toYaml .Values.workers.resources | nindent 12 }}
      {{- with .Values.workers.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workers.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workers.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
